// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzdi-4l_V0bZnZ44b8PwsTaLm_vZELRw',
    appId: '1:529825384215:web:849e69179728ea033b5952',
    messagingSenderId: '529825384215',
    projectId: 'mycoffeeshop-bf177',
    authDomain: 'mycoffeeshop-bf177.firebaseapp.com',
    storageBucket: 'mycoffeeshop-bf177.appspot.com',
    measurementId: 'G-GCVDF5SES0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGSvsw7oU8EY4xtsc4DByMx0he3O7wai8',
    appId: '1:529825384215:android:a623b0e06ff379823b5952',
    messagingSenderId: '529825384215',
    projectId: 'mycoffeeshop-bf177',
    storageBucket: 'mycoffeeshop-bf177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBmY4lR9ho-_PIZusLodh7PTbykHUb5o',
    appId: '1:529825384215:ios:2597be3153fbcf2b3b5952',
    messagingSenderId: '529825384215',
    projectId: 'mycoffeeshop-bf177',
    storageBucket: 'mycoffeeshop-bf177.appspot.com',
    iosClientId: '529825384215-q2fca9j3cor9c3bfsnsc4q4ehdur65rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRBmY4lR9ho-_PIZusLodh7PTbykHUb5o',
    appId: '1:529825384215:ios:2597be3153fbcf2b3b5952',
    messagingSenderId: '529825384215',
    projectId: 'mycoffeeshop-bf177',
    storageBucket: 'mycoffeeshop-bf177.appspot.com',
    iosClientId: '529825384215-q2fca9j3cor9c3bfsnsc4q4ehdur65rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeShop',
  );
}
